# RPI Student Senate website
#          #WTG
version: "3"
services: 
  web:
    image: wordpress:latest
    links: 
     - "db:database"
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    ports:
      - "8000:80"
    volumes: 
      - ./wp-content:/var/www/html/wp-content
  db:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
